project_id = "exsjjyoqybsajgaconee"

[functions.create-topup]
verify_jwt = false

[functions.midtrans-webhook]
verify_jwt = false

[functions.purchase-credits]
verify_jwt = false

[functions.create-order-payment]
verify_jwt = false

[functions.send-order-notification]
verify_jwt = false
